config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/home/about' => 'homes#about', as: "about"
  devise_for :users

  resources :books, only: [:show, :index, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get 'tagsearches/search', to: 'tagsearches#search'
  post 'tagsearches/search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}


  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :category, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups, dependent: :destroy

  belongs_to :owner, class_name: 'User'
  has_many :users, through: :user_groups, source: :user

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image

  def get_group_image(width, height)
    unless group_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      group_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    group_image.variant(resize_to_limit: [width, height]).processed
  end

  def is_owned_by?(user)
    owner_id == user.id
  end

  def includesUser?(user)
    user_groups.exists?(user_id: user.id)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, length: { minimum: 1, maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_groups, dependent: :destroy

  # フォローをした、されたの関係
  has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :following_relationships, source: :followed
  has_many :followers, through: :followed_relationships, source: :follower

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # フォローしたときの処理
  def follow(user_id)
    following_relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    following_relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @current_user = current_user
    @book = Book.new
    @book_comments = BookComment.all
    if params[:latest]
     @books = Book.latest
    elsif params[:old]
     @books = Book.old
    elsif params[:star_count]
     @books = Book.star_count
    else
     @books = Book.all
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.user_name = current_user.name
    if @book.save
      flash[:notice] = "successfully created"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if @user == current_user
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @new_comment = BookComment.new
    @book_comments = BookComment.all
    @user = @book.user
    @current_user = current_user
  end

  def destroy
    @book = Book.find(params[:id])
    @user = @book.user
    if @user == current_user
    else
      redirect_to books_path
    end
    @book.destroy
    flash[:notice] = "successfully deleted."
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :category)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/tagsearches_helper.rb
module TagsearchesHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_otherinfo.html.erb
  <h2>Others info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th>
          <%= link_to user.followings.count, user_followings_path(user.id) %>
        </th>
      </tr>
      <tr>
        <th>followers</th>
        <th>
          <%= link_to user.followers.count, user_followers_path(user.id) %>
        </th>
      </tr>
    </tbody>
  </table>


  <div class="row">
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>

    <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
     <%= link_to 'チャットを始める', message_path(user.id), class: "ml-3" %>
    <% end %>
  </div>


  <div class="row">
    <h2 class="mt-3">New book</h2>
    <%= form_with model: book do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>

      <h4>Opinion</h4>
      <%= f.text_area :body %>

      <%= f.submit "Create Book" %>
    <% end %>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="con-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    
      <% if @book.errors.any? %>
        <%= @book.errors.count %>件のerrorが発生しました
        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>

      <h1>Editing Book</h1>

      <%= form_with model: @book do |f| %>

        <p class="form_text"><label for="inputTitle">Title</label></p>
        <%= f.text_field :title, autofocus:true, id:"inputTitle", placeholder:"名前" %>

        <p class="form_text"><label for="inputBody">Opinion</label></p>
        <%= f.text_area :body, autofocus:true, id:"inputBody", placeholder:"感想" %>

        <div class="action">
         <%= f.submit " Update Book " %>
        </div>

      <% end %>

      <div class="a"><%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", "/books" %></div>


    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="text-success">
  <%= flash[:notice] %>
</div>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <%= render 'layouts/side_bar', book: @book, user: current_user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= link_to '新しい順', books_path(latest: "true") %>
      |<%= link_to '古い順', books_path(old: "true") %>
      |<%= link_to '評価の高い順', books_path(star_count: "true") %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="6"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
                <br>
                <%= link_to book.user.name, user_path(book.user.id) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td id="favorite_buttons_<%= book.id %>">
              <%= render 'layouts/favorite_btn', book: book %>
            </td>
            <td><p>コメント数: <%= book.book_comments.count %></p></td>
            <td><div id="star_<%= book.id %>"></div></td>
            <script>
            $(document).on('turbolinks:load', function() {
              let elem = document.querySelector('#star_<%= book.id %>');
              if (elem == null) return;

              elem.innerHTML = "";
              let opt = {
                starOn: "<%= asset_path('star-on.png') %>",
                starOff: "<%= asset_path('star-off.png') %>",
                starHalf: "<%= asset_path('star-half.png') %>",
                score: "<%= book.star %>",
                readOnly: true,
              };
              raty(elem, opt);
            });
            </script>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="text-success">
  <%= flash[:notice] %>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'layouts/side_bar', book: @new_book, user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">

        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= image_tag @user.get_profile_image(100,100) %>
                <br>
                <%= @user.name %>
              <% end %>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), method: :delete, data_confirm: "本当に消しますか？", class: "btn btn-sm btn-danger" %></td>
            <% end %>

            <td id="favorite_buttons_<%= @book.id %>">
              <%= render 'layouts/favorite_btn', book: @book %>
            </td>

            <td id="comments_count">
              <%= render 'layouts/comments_count', book: @book %>
            </td>
            <td><div id="star_<%= @book.id %>"></div></td>
            <td>
          　　<% if @book.category.present? %>
          　　　　<%=link_to@book.category,tagsearches_search_path(content:@book.category)%>
          　　<% end %>
            </td>
            <script>
              $(document).on('turbolinks:load', function() {
                let elem = document.querySelector('#star_<%= @book.id %>');
                if (elem == null) return;

                elem.innerHTML = "";
                let opt = {
                  starOn: "<%= asset_path('star-on.png') %>",
                  starOff: "<%= asset_path('star-off.png') %>",
                  starHalf: "<%= asset_path('star-half.png') %>",
                  score: "<%= @book.star %>",
                  readOnly: true,
                };
                raty(elem, opt);
              });
            </script>
          </tr>
        </tbody>

        <tbody id="book_comment_field">
          <%= render 'layouts/book_comment_field', book: @book, book_comment: @new_comment %>
        </tbody>

      </table>
    </div>
  </div>
</div>