config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/home/about' => 'homes#about', as: "about"
  devise_for :users

  resources :books, only: [:show, :index, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get 'tagsearches/search', to: 'tagsearches#search'
  post 'tagsearches/search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}


  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :category, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups, dependent: :destroy

  belongs_to :owner, class_name: 'User'
  has_many :users, through: :user_groups, source: :user

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image

  def get_group_image(width, height)
    unless group_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      group_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    group_image.variant(resize_to_limit: [width, height]).processed
  end

  def is_owned_by?(user)
    owner_id == user.id
  end

  def includesUser?(user)
    user_groups.exists?(user_id: user.id)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, length: { minimum: 1, maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_groups, dependent: :destroy

  # フォローをした、されたの関係
  has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :following_relationships, source: :followed
  has_many :followers, through: :followed_relationships, source: :follower

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # フォローしたときの処理
  def follow(user_id)
    following_relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    following_relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/tagsearches_helper.rb
module TagsearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_book_comment_field.html.erb
<% book.book_comments.each do |book_comment| %>
  <tr>
    <td>
      <%= link_to user_path(book_comment.user_id) do %>
        <%= image_tag book_comment.user.get_profile_image(80,80) %>
        <br>
        <%= link_to book_comment.user.name, user_path(book_comment.user_id) %>
      <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <% if book_comment.user_id == current_user.id %>
      <td><%= link_to "Destroy", book_book_comment_path(book_comment.book_id, book_comment), method: :delete, remote: true, data_confirm: "本当に消しますか？", class: "btn btn-sm btn-danger" %></td>
    <% end %>
  </tr>
  <% end %>
  <tr>
    <td colspan="6">
      <%= form_with model: [book, book_comment], local: false do |f| %>
       <%= f.text_area :comment, cols: '40', rows: '5', placeholder: "コメントをここに" %>
       <%= f.submit "送信" %>
      <% end %>
     </td>
   </tr>

app/views/layouts/_comments_count.html.erb
<p>コメント数: <%= book.book_comments.count %></p>

app/views/layouts/_favorite_btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
  <i class="fas fa-heart"></i> <%= book.favorites.count %> いいね
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
  <i class="fa-regular fa-heart"></i> <%= book.favorites.count %> いいね
  <% end %>
<% end %>

app/views/layouts/_follow_btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user_id), method: :delete %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user_id), method: :post %>
  <% end %>
<% end %>

app/views/layouts/_search.html.erb
<h4>検索結果</h4>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/layouts/_side_bar.html.erb
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th>
          <%= link_to user.followings.count, user_followings_path(user.id) %>
        </th>
      </tr>
      <tr>
        <th>followers</th>
        <th>
          <%= link_to user.followers.count, user_followers_path(user.id) %>
        </th>
      </tr>
    </tbody>
  </table>


  <div class="row">
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>


  <div class="row">
    <h2 class="mt-3">New book</h2>
    <%= form_with model: book do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>

      <h4>Opinion</h4>
      <%= f.text_area :body %>

      <div class="form-group" id="star">
       <h4><%= f.label :star %></h4>
        <%= f.hidden_field :star, id: :review_star, class: 'form-control' %>
        <div id="post_raty"></div>
      </div>
      <script>
        $(document).on('turbolinks:load', function() {
          let elem = document.querySelector('#post_raty');
          if (elem == null) return;

          elem.innerHTML = ""
          let opt = {
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            scoreName: 'book[star]',
          };
          raty(elem, opt);
        });
      </script>

      <div class="form-group">
        <h4><%= f.label :Category %></h4>
        <%= f.text_field :category,class: 'form-control book_category' %>
      </div>

      <%= f.submit "Create Book" %>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <body class="d-flex flex-column vh-100">

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>

          <button class="navbar-toggler" type=ru"button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expand="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <a class="nav-link text-light" href="/users">
                  <i class="fas fa-users"></i> Users
                </a>
              </li>
              <li>
                <a class="nav-link text-light" href="/books">
                  <i class="fas fa-book-open"></i> Books
                </a>
              </li>
              <li>
                <%= link_to destroy_user_session_path, class: "nav-link text-light", method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i> logout
                <% end %>
              </li>
              <% else %>
              <li>
                <a class="nav-link text-light" href="/">
                  <i class="fas fa-home"></i> Home
                </a>
              </li>
              <li>
               <a class="nav-link text-light" href= "/home/about" >
                  <i class="fas fa-link"></i> About
                </a>
              </li>
              <li>
                <a class="nav-link text-light" href="/users/sign_up">
                  <i class="fas fa-user-plus"></i> sign up
                </a>
              </li>
              <li>
                <a class="nav-link text-light" href="/users/sign_in">
                  <i class="fas fa-sign-in-alt"></i> login
                </a>
              </li>
              <% end %>
            </ul>
          </div>
         </div>
      </nav>
    </header>

    <main class="pt-3">
    <% if user_signed_in? %>
      <%= render 'tagsearches/tagsearch' %>
    <% end %>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>